Create a python program to find duplicate files by content. User will 
input path and it will scan all directories, sub-directories to find all 
duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]

In [2]:
import sys
import os
import hashlib

p=input("Enter the file : ")
files = os.listdir(p)
directory = []
for (dir_path, dir_name, files_name) in os.walk(p):
    directory.extend(files_name)
    
#print(directory)
hash_of_file=[]

hash_del=[]
parent_path = "D:/pyfile/"
for files_name in directory:
    path = os.path.join(parent_path,files_name)
    fileobj1 = open(path, "r")
    string1=fileobj1.read()
    fileobj1.close()
    message = hashlib.sha256()
    message.update(string1.encode())
    file_hash = message.hexdigest()
    if file_hash not in hash_of_file:
        hash_of_file.append(file_hash)
    else:
        hash_del.append(files_name)

print(hash_del)
for files_name in hash_del:
    path = os.path.join(parent_path,files_name)
    if os.path.isfile(path):
        os.remove(path)
        print("Duplicate file "+ files_name +" deleted successfully")
    else:
        print("Error: %s file not found" % files_name)

Enter the file : D:/pyfile
['test2.txt']
Duplicate file test2.txt deleted successfully


Generate random Password with exact length = 6, with minimum 1 
uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]

In [19]:
import random
import string

str2=""
s=random.choice(string.ascii_uppercase)
str2=str2+s
for i in range(2):
    str1 = random.choice(string.ascii_lowercase)
    str2 = str2+str1
for i in range(3):
    n=random.randint(0,9)
    str2=str2+str(n)

lst = []
lst.extend(str2)

random.shuffle(lst)

str3=""
print("Random Password : ",str3.join(lst))

Random Password :  yY111r


Create 2D array and update the same 2D array provided that every 
prime number position should be replaced by cube of the positioned 
number.

In [26]:
import numpy as np

arr=np.arange(0,16).reshape(4,4)

for i in range(4):
    for j in range(4):
        flag = False
        for k in range(2, arr[i][j]):
             if (arr[i][j] % k) == 0:
                    flag = True
                    break
        if (flag == False):
            arr[i][j]=arr[i][j]*arr[i][j]*arr[i][j]
            

arr

array([[   0,    1,    8,   27],
       [   4,  125,    6,  343],
       [   8,    9,   10, 1331],
       [  12, 2197,   14,   15]])

Python program to get the sum of every cubed value and its previous integer. 
# ( x + y^3 )

In [10]:
import numpy as np

lst = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

for i in range(1,len(lst)):
    flag = False
    for k in range(2,lst[i]):
        if(lst[i]%k == 0):
            flag = True
            break
    if(flag == False):
        lst[i] = lst[i-1] + (lst[i]*lst[i]*lst[i])

arr = np.array(lst).reshape(4,4)
arr

array([[   0,    1,    9,   36],
       [   4,  129,    6,  349],
       [   8,    9,   10, 1341],
       [  12, 2209,   14,   15]])

Given two arrays, find their intersection. Examples:
Input:  arr1[] = [1, 3, 4, 5, 7]
             arr2[] = [2, 3, 5, 6]

In [21]:
arr1 = np.array([1, 3, 4, 5, 7])
arr2 = np.array([2, 3, 5, 6])

np.intersect1d(arr1,arr2)

array([3, 5])

Create a 7 x 7  2D array having only multiples of 7. And return the last 
element of the same.

In [22]:
arr=np.arange(1,50).reshape(7,7)
arr=arr*7
print(arr)
arr.max()

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]


343

Checker Board Patten using Numpy:
[   1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1  ]

In [23]:
arr = np.ones((7,5))
arr[1::2,0::2] = 0
arr[0::2,1::2] = 0
arr

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

Create a given Matrix:
[  A,     B,     C,       D
   E,      F,     G,       H
    I,      a,      K,       L
   M,    N,     o,       P
   Q,     R,      S,       T
   U,     0,     W,      O ]
Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values

In [24]:
import random
import string 

arr=np.empty((6,4),dtype="object")

for i in range(6):
    for j in range(4):
        arr[i][j] = random.choice(string.ascii_uppercase)
        

count=0;
for i in range(6):
    for j in range(4):
        if(arr[i][j] == 'A' or arr[i][j] == 'E' or arr[i][j] == 'I' or arr[i][j] == 'O' or arr[i][j] == 'U'):
            arr[i][j] = str(np.nan)
            count+=1


print(count)
arr

5


array([['nan', 'R', 'N', 'X'],
       ['S', 'Q', 'N', 'Z'],
       ['G', 'nan', 'B', 'T'],
       ['nan', 'S', 'H', 'Z'],
       ['P', 'F', 'V', 'K'],
       ['nan', 'S', 'Z', 'nan']], dtype=object)